public class devop {
public void Method1(){
        integer a= 6;
        integer b= 9;
        integer Re= a+b;
        system.debug(' Non paramatrized constructor==> Addioon is'+re);
                    
        } 
    public void method2(integer a, integer b){
       Integer re= a+b;
       system.debug('Non Pramatrized==> addition'+re);
        
    }
	public void method3(integer a, integer b){
       Integer re= a+b;
        system.debug('Non Pramatrized==> addition'+re);
    }
  			
}